### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr12"
    scheme   = "https"
    address  = "sr12.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r121" {
  name =  "r121"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:42:53:01"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.240/32   
    - 2001:41d0:2:c234::1/128
    gateway6: 2001:41d0:2:c234::1 
    gateway4: 54.38.6.240
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r122" {
  name =  "r122"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:8b:67:2b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.241/32   
    - 2001:41d0:2:c234::2/128
    gateway6: 2001:41d0:2:c234::2 
    gateway4: 54.38.6.241
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r123" {
  name =  "r123"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:b0:fb:15"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.242/32   
    - 2001:41d0:2:c234::3/128
    gateway6: 2001:41d0:2:c234::3 
    gateway4: 54.38.6.242
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r124" {
  name =  "r124"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:d3:1a:65"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.243/32   
    - 2001:41d0:2:c234::4/128
    gateway6: 2001:41d0:2:c234::4 
    gateway4: 54.38.6.243
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r125" {
  name =  "r125"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:19:b9:1a"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.244/32   
    - 2001:41d0:2:c234::5/128
    gateway6: 2001:41d0:2:c234::5 
    gateway4: 54.38.6.244
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r126" {
  name =  "r126"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:65:3d:4f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.245/32   
    - 2001:41d0:2:c234::6/128
    gateway6: 2001:41d0:2:c234::6 
    gateway4: 54.38.6.245
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r127" {
  name =  "r127"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:40:5f:e3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.246/32   
    - 2001:41d0:2:c234::7/128
    gateway6: 2001:41d0:2:c234::7 
    gateway4: 54.38.6.246
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r128" {
  name =  "r128"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:52:50:0c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.6.247/32   
    - 2001:41d0:2:c234::8/128
    gateway6: 2001:41d0:2:c234::8 
    gateway4: 54.38.6.247
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r129" {
  name =  "r129"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:65:fd:9c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.192/32   
    - 2001:41d0:2:c234::9/128
    gateway6: 2001:41d0:2:c234::9 
    gateway4: 145.239.59.192
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12a" {
  name =  "r12a"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:af:7b:4b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.193/32   
    - 2001:41d0:2:c234::a/128
    gateway6: 2001:41d0:2:c234::a 
    gateway4: 145.239.59.193
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12b" {
  name =  "r12b"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:da:05:32"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.194/32   
    - 2001:41d0:2:c234::b/128
    gateway6: 2001:41d0:2:c234::b 
    gateway4: 145.239.59.194
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12c" {
  name =  "r12c"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:11:65:5a"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.195/32   
    - 2001:41d0:2:c234::c/128
    gateway6: 2001:41d0:2:c234::c 
    gateway4: 145.239.59.195
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12d" {
  name =  "r12d"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:ac:ce:67"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.196/32   
    - 2001:41d0:2:c234::d/128
    gateway6: 2001:41d0:2:c234::d 
    gateway4: 145.239.59.196
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12e" {
  name =  "r12e"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:68:26:ca"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.197/32   
    - 2001:41d0:2:c234::e/128
    gateway6: 2001:41d0:2:c234::e 
    gateway4: 145.239.59.197
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12f" {
  name =  "r12f"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:c7:fc:00"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.198/32   
    - 2001:41d0:2:c234::f/128
    gateway6: 2001:41d0:2:c234::f 
    gateway4: 145.239.59.198
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r12g" {
  name =  "r12g"
  image     = "zen-base"
  remote = "sr12"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:7b:9a:21"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.59.199/32   
    - 2001:41d0:2:c234::10/128
    gateway6: 2001:41d0:2:c234::10 
    gateway4: 145.239.59.199
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}

