### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr14"
    scheme   = "https"
    address  = "sr14.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r141" {
  name =  "r141"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:10:bd:c4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.36.30.172/32   
    - 2001:41d0:2:cf98::1/128
    gateway6: 2001:41d0:2:cf98::1 
    gateway4: 54.36.30.172
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r142" {
  name =  "r142"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:45:1e:50"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.36.30.173/32   
    - 2001:41d0:2:cf98::2/128
    gateway6: 2001:41d0:2:cf98::2 
    gateway4: 54.36.30.173
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r143" {
  name =  "r143"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:39:f4:9b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.36.30.174/32   
    - 2001:41d0:2:cf98::3/128
    gateway6: 2001:41d0:2:cf98::3 
    gateway4: 54.36.30.174
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r144" {
  name =  "r144"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:d1:f0:12"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.36.30.175/32   
    - 2001:41d0:2:cf98::4/128
    gateway6: 2001:41d0:2:cf98::4 
    gateway4: 54.36.30.175
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r145" {
  name =  "r145"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:76:91:f5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.88/32   
    - 2001:41d0:2:cf98::5/128
    gateway6: 2001:41d0:2:cf98::5 
    gateway4: 54.38.233.88
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r146" {
  name =  "r146"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:6c:b2:61"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.89/32   
    - 2001:41d0:2:cf98::6/128
    gateway6: 2001:41d0:2:cf98::6 
    gateway4: 54.38.233.89
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r147" {
  name =  "r147"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:d1:fa:fa"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.90/32   
    - 2001:41d0:2:cf98::7/128
    gateway6: 2001:41d0:2:cf98::7 
    gateway4: 54.38.233.90
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r148" {
  name =  "r148"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:8f:5d:cc"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.91/32   
    - 2001:41d0:2:cf98::8/128
    gateway6: 2001:41d0:2:cf98::8 
    gateway4: 54.38.233.91
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r149" {
  name =  "r149"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:51:56:f8"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.92/32   
    - 2001:41d0:2:cf98::9/128
    gateway6: 2001:41d0:2:cf98::9 
    gateway4: 54.38.233.92
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14a" {
  name =  "r14a"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e0:0f:3f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.93/32   
    - 2001:41d0:2:cf98::a/128
    gateway6: 2001:41d0:2:cf98::a 
    gateway4: 54.38.233.93
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14b" {
  name =  "r14b"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e9:c8:3d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.94/32   
    - 2001:41d0:2:cf98::b/128
    gateway6: 2001:41d0:2:cf98::b 
    gateway4: 54.38.233.94
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14c" {
  name =  "r14c"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:43:18:fb"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.95/32   
    - 2001:41d0:2:cf98::c/128
    gateway6: 2001:41d0:2:cf98::c 
    gateway4: 54.38.233.95
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14d" {
  name =  "r14d"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e4:3a:61"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.96/32   
    - 2001:41d0:2:cf98::d/128
    gateway6: 2001:41d0:2:cf98::d 
    gateway4: 54.38.233.96
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14e" {
  name =  "r14e"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:dc:58:1f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.97/32   
    - 2001:41d0:2:cf98::e/128
    gateway6: 2001:41d0:2:cf98::e 
    gateway4: 54.38.233.97
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14f" {
  name =  "r14f"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:a8:61:eb"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.98/32   
    - 2001:41d0:2:cf98::f/128
    gateway6: 2001:41d0:2:cf98::f 
    gateway4: 54.38.233.98
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r14g" {
  name =  "r14g"
  image     = "zen-base"
  remote = "sr14"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:9a:b7:34"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 54.38.233.99/32   
    - 2001:41d0:2:cf98::10/128
    gateway6: 2001:41d0:2:cf98::10 
    gateway4: 54.38.233.99
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}

