### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sb08"
    scheme   = "https"
    address  = "sb08.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "znode43" {
  name =  "znode43"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:8e:76:ba"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.80/32   
    gateway4: 142.44.193.80
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode44" {
  name =  "znode44"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:a8:d1:99"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.81/32   
    gateway4: 142.44.193.81
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode47" {
  name =  "znode47"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:b8:08:c7"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.82/32   
    gateway4: 142.44.193.82
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode48" {
  name =  "znode48"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:1b:61:7d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.83/32   
    gateway4: 142.44.193.83
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode16" {
  name =  "znode16"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:dc:91:f3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.84/32   
    gateway4: 142.44.193.84
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode20" {
  name =  "znode20"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:0c:7d:28"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.85/32   
    gateway4: 142.44.193.85
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode21" {
  name =  "znode21"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:12:e9:89"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.86/32   
    gateway4: 142.44.193.86
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "znode42" {
  name =  "znode42"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:e6:8f:c1"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 142.44.193.87/32   
    gateway4: 142.44.193.87
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0g" {
  name =  "zen-b0g"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:c4:61:06"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.248/32   
    gateway4: 158.69.156.248
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0h" {
  name =  "zen-b0h"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:bd:96:19"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.249/32   
    gateway4: 158.69.156.249
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0i" {
  name =  "zen-b0i"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:a3:8e:d1"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.250/32   
    gateway4: 158.69.156.250
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0j" {
  name =  "zen-b0j"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:98:79:6b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.251/32   
    gateway4: 158.69.156.251
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0k" {
  name =  "zen-b0k"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:55:0f:7d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.252/32   
    gateway4: 158.69.156.252
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0l" {
  name =  "zen-b0l"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:a5:b3:0a"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.253/32   
    gateway4: 158.69.156.253
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0m" {
  name =  "zen-b0m"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:1f:5e:76"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.254/32   
    gateway4: 158.69.156.254
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "zen-b0n" {
  name =  "zen-b0n"
  image     = "zen-base"
  remote = "sb08"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d4:d1:15"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 158.69.156.255/32   
    gateway4: 158.69.156.255
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}

