### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr06"
    scheme   = "https"
    address  = "sr06.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}



resource "lxd_container" "zen-a6a" {
  name =  "zen-a6a"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:3d:5f:23"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.95.228/32
    gateway4: 213.32.95.228
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6b" {
  name =  "zen-a6b"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:34:5e:36"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.95.229/32
    gateway4: 213.32.95.229
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6c" {
  name =  "zen-a6c"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:7b:85:94"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.95.230/32
    gateway4: 213.32.95.230
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6d" {
  name =  "zen-a6d"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:25:7b:c4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.95.231/32
    gateway4: 213.32.95.231
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6e" {
  name =  "zen-a6e"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:49:a1:a3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.104/32
    gateway4: 193.70.52.104
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6f" {
  name =  "zen-a6f"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:57:7a:88"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.105/32
    gateway4: 193.70.52.105
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6g" {
  name =  "zen-a6g"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:94:10:8b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.106/32
    gateway4: 193.70.52.106
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6h" {
  name =  "zen-a6h"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:e6:2a:2c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.107/32
    gateway4: 193.70.52.107
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6i" {
  name =  "zen-a6i"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:77:0d:2b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.108/32
    gateway4: 193.70.52.108
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6j" {
  name =  "zen-a6j"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:b2:7f:41"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.109/32
    gateway4: 193.70.52.109
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6k" {
  name =  "zen-a6k"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:87:ed:d5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.110/32
    gateway4: 193.70.52.110
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6m" {
  name =  "zen-a6m"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:a3:f8:3e"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 193.70.52.111/32
    gateway4: 193.70.52.111
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1g" {
  name =  "zen-b1g"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:b5:72:17"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 176.31.14.180/32
    gateway4: 176.31.14.180
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1h" {
  name =  "zen-b1h"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:43:e2:ab"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 176.31.14.181/32
    gateway4: 176.31.14.181
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1i" {
  name =  "zen-b1i"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:ce:1b:90"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 176.31.14.182/32
    gateway4: 176.31.14.182
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1j" {
  name =  "zen-b1j"
  image     = "zen-base"
  remote = "sr06"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:48:d0:f3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 176.31.14.183/32
    gateway4: 176.31.14.183
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}

