### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr11"
    scheme   = "https"
    address  = "sr11.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r111" {
  name =  "r111"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:19:36:3a"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.0/32   
    - 2001:41d0:8:5120::1/128
    gateway6: 2001:41d0:8:5120::1 
    gateway4: 145.239.174.0
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r112" {
  name =  "r112"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e6:40:f5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.1/32   
    - 2001:41d0:8:5120::2/128
    gateway6: 2001:41d0:8:5120::2 
    gateway4: 145.239.174.1
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r113" {
  name =  "r113"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:06:a3:e4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.2/32   
    - 2001:41d0:8:5120::3/128
    gateway6: 2001:41d0:8:5120::3 
    gateway4: 145.239.174.2
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r114" {
  name =  "r114"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:f1:53:2f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.3/32   
    - 2001:41d0:8:5120::4/128
    gateway6: 2001:41d0:8:5120::4 
    gateway4: 145.239.174.3
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r115" {
  name =  "r115"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:1a:e4:9a"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.4/32   
    - 2001:41d0:8:5120::5/128
    gateway6: 2001:41d0:8:5120::5 
    gateway4: 145.239.174.4
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r116" {
  name =  "r116"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:3b:e1:f1"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.5/32   
    - 2001:41d0:8:5120::6/128
    gateway6: 2001:41d0:8:5120::6 
    gateway4: 145.239.174.5
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r117" {
  name =  "r117"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e0:25:31"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.6/32   
    - 2001:41d0:8:5120::7/128
    gateway6: 2001:41d0:8:5120::7 
    gateway4: 145.239.174.6
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r118" {
  name =  "r118"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:88:42:39"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.7/32   
    - 2001:41d0:8:5120::8/128
    gateway6: 2001:41d0:8:5120::8 
    gateway4: 145.239.174.7
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r119" {
  name =  "r119"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:be:77:c4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.8/32   
    - 2001:41d0:8:5120::9/128
    gateway6: 2001:41d0:8:5120::9 
    gateway4: 145.239.174.8
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11a" {
  name =  "r11a"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:98:2e:b4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.9/32   
    - 2001:41d0:8:5120::a/128
    gateway6: 2001:41d0:8:5120::a 
    gateway4: 145.239.174.9
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11b" {
  name =  "r11b"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:92:b1:4d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.10/32   
    - 2001:41d0:8:5120::b/128
    gateway6: 2001:41d0:8:5120::b 
    gateway4: 145.239.174.10
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11c" {
  name =  "r11c"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:ec:bd:bf"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.11/32   
    - 2001:41d0:8:5120::c/128
    gateway6: 2001:41d0:8:5120::c 
    gateway4: 145.239.174.11
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11d" {
  name =  "r11d"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:dc:43:42"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.12/32   
    - 2001:41d0:8:5120::d/128
    gateway6: 2001:41d0:8:5120::d 
    gateway4: 145.239.174.12
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11e" {
  name =  "r11e"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:26:c0:84"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.13/32   
    - 2001:41d0:8:5120::e/128
    gateway6: 2001:41d0:8:5120::e 
    gateway4: 145.239.174.13
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11f" {
  name =  "r11f"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:5f:e9:81"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.14/32   
    - 2001:41d0:8:5120::f/128
    gateway6: 2001:41d0:8:5120::f 
    gateway4: 145.239.174.14
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r11g" {
  name =  "r11g"
  image     = "zen-base"
  remote = "sr11"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e8:d7:25"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.174.15/32   
    - 2001:41d0:8:5120::10/128
    gateway6: 2001:41d0:8:5120::10 
    gateway4: 145.239.174.15
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}

