### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr07"
    scheme   = "https"
    address  = "sr07.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}



resource "lxd_container" "zen-a6n" {
  name =  "zen-a6n"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:e0:f2:71"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 91.121.225.168/32
    gateway4: 91.121.225.168
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6p" {
  name =  "zen-a6p"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d4:ef:33"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 91.121.225.169/32
    gateway4: 91.121.225.169
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6q" {
  name =  "zen-a6q"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:45:f7:04"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 91.121.225.170/32
    gateway4: 91.121.225.170
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6r" {
  name =  "zen-a6r"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d6:e2:d8"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 91.121.225.171/32
    gateway4: 91.121.225.171
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6s" {
  name =  "zen-a6s"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:64:eb:a0"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.200/32
    gateway4: 5.196.158.200
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6t" {
  name =  "zen-a6t"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:3b:03:46"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.201/32
    gateway4: 5.196.158.201
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6u" {
  name =  "zen-a6u"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:97:a8:0b"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.202/32
    gateway4: 5.196.158.202
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6v" {
  name =  "zen-a6v"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:fd:ae:89"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.203/32
    gateway4: 5.196.158.203
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6w" {
  name =  "zen-a6w"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:ea:89:27"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.204/32
    gateway4: 5.196.158.204
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6x" {
  name =  "zen-a6x"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:1e:38:48"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.205/32
    gateway4: 5.196.158.205
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6y" {
  name =  "zen-a6y"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:2b:96:04"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.206/32
    gateway4: 5.196.158.206
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-a6z" {
  name =  "zen-a6z"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:79:f5:86"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.196.158.207/32
    gateway4: 5.196.158.207
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1k" {
  name =  "zen-b1k"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:75:26:a8"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.135.204.96/32
    gateway4: 5.135.204.96
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1l" {
  name =  "zen-b1l"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d5:fe:7d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.135.204.97/32
    gateway4: 5.135.204.97
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1m" {
  name =  "zen-b1m"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:9f:9d:a4"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.135.204.98/32
    gateway4: 5.135.204.98
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}


resource "lxd_container" "zen-b1n" {
  name =  "zen-b1n"
  image     = "zen-base"
  remote = "sr07"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:f6:75:af"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 5.135.204.99/32
    gateway4: 5.135.204.99
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}

