#!/usr/bin/env bash

t_addr=$(zen-cli listaddresses | jq -r '.[0]')
t_key=$(zen-cli dumpprivkey $t_addr)
t_balance=$(zen-cli z_gettotalbalance | jq -r '.transparent')
z_addr_0=$(zen-cli z_listaddresses | jq -r '.[0]')
z_balance_0=$(zen-cli z_getbalance $z_addr_0)
z_key_0=$(zen-cli z_exportkey $z_addr_0)
z_addr_1=$(zen-cli z_listaddresses | jq -r '.[1]')
z_balance_1=$(zen-cli z_getbalance $z_addr_1)
z_key_1=$(zen-cli z_exportkey $z_addr_1)
z_balance=$(zen-cli z_gettotalbalance | jq -r '.private')
balance=$(zen-cli z_gettotalbalance | jq -r '.total')
node_id=$(cat ~/secnodetracker/config/nodeid)
zen_home=securenodes$(cat ~/secnodetracker/config/home | sed s/^ts1/ts/ | sed s/^ts//).zensystem.io
email=$(cat /home/zen/secnodetracker/config/email)
region=$(cat /home/zen/secnodetracker/config/region)
stake_addr=$(cat /home/zen/secnodetracker/config/stakeaddr)
node_detail_url=https://$zen_home/nodes/$node_id/detail

echo "\"$t_addr\",\"$t_key\",$t_balance,\"$z_addr_0\",\"$z_key_0\",$z_balance_0,\"$z_addr_1\",\"$z_key_1\",$z_balance_1,$balance,$node_id,\"$email\",\"$region\",\"$node_detail_url\",\"$stake_addr\""
