#!/usr/bin/env bash

for remote in $(lxc remote list | grep -o "s[bgr][01][0-9] "); do
  for node in $(lxc list $remote:  | grep -o "z[en][no][-d][ae].."); do
    ssh -o StrictHostKeyChecking=accept-new zen@$node zen-cli listaddresses | jq -r .[0]
  done
done
