### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr13"
    scheme   = "https"
    address  = "sr13.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r131" {
  name =  "r131"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:a3:37:5d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.240.144/32   
    - 2001:41d0:2:243c::1/128
    gateway6: 2001:41d0:2:243c::1 
    gateway4: 147.135.240.144
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r132" {
  name =  "r132"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:1a:af:7e"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.240.145/32   
    - 2001:41d0:2:243c::2/128
    gateway6: 2001:41d0:2:243c::2 
    gateway4: 147.135.240.145
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r133" {
  name =  "r133"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:f0:69:b0"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.240.146/32   
    - 2001:41d0:2:243c::3/128
    gateway6: 2001:41d0:2:243c::3 
    gateway4: 147.135.240.146
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r134" {
  name =  "r134"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:57:30:f0"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.240.147/32   
    - 2001:41d0:2:243c::4/128
    gateway6: 2001:41d0:2:243c::4 
    gateway4: 147.135.240.147
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r135" {
  name =  "r135"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:0d:b0:74"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 46.105.137.248/32   
    - 2001:41d0:2:243c::5/128
    gateway6: 2001:41d0:2:243c::5 
    gateway4: 46.105.137.248
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r136" {
  name =  "r136"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:bb:a6:ec"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 46.105.137.249/32   
    - 2001:41d0:2:243c::6/128
    gateway6: 2001:41d0:2:243c::6 
    gateway4: 46.105.137.249
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r137" {
  name =  "r137"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:d5:af:4c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 46.105.137.250/32   
    - 2001:41d0:2:243c::7/128
    gateway6: 2001:41d0:2:243c::7 
    gateway4: 46.105.137.250
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r138" {
  name =  "r138"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:4e:fe:09"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 46.105.137.251/32   
    - 2001:41d0:2:243c::8/128
    gateway6: 2001:41d0:2:243c::8 
    gateway4: 46.105.137.251
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r139" {
  name =  "r139"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:23:0b:73"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.224/32   
    - 2001:41d0:2:243c::9/128
    gateway6: 2001:41d0:2:243c::9 
    gateway4: 145.239.122.224
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13a" {
  name =  "r13a"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:b2:df:a2"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.225/32   
    - 2001:41d0:2:243c::a/128
    gateway6: 2001:41d0:2:243c::a 
    gateway4: 145.239.122.225
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13b" {
  name =  "r13b"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:f1:41:bd"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.226/32   
    - 2001:41d0:2:243c::b/128
    gateway6: 2001:41d0:2:243c::b 
    gateway4: 145.239.122.226
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13c" {
  name =  "r13c"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:e5:c5:2c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.227/32   
    - 2001:41d0:2:243c::c/128
    gateway6: 2001:41d0:2:243c::c 
    gateway4: 145.239.122.227
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13d" {
  name =  "r13d"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:5d:97:59"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.228/32   
    - 2001:41d0:2:243c::d/128
    gateway6: 2001:41d0:2:243c::d 
    gateway4: 145.239.122.228
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13e" {
  name =  "r13e"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:50:c1:fb"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.229/32   
    - 2001:41d0:2:243c::e/128
    gateway6: 2001:41d0:2:243c::e 
    gateway4: 145.239.122.229
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13f" {
  name =  "r13f"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:7d:96:c5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.230/32   
    - 2001:41d0:2:243c::f/128
    gateway6: 2001:41d0:2:243c::f 
    gateway4: 145.239.122.230
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r13g" {
  name =  "r13g"
  image     = "zen-base"
  remote = "sr13"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "enp3s0"
      hwaddr = "02:00:00:dc:dd:9c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.231/32   
    - 2001:41d0:2:243c::10/128
    gateway6: 2001:41d0:2:243c::10 
    gateway4: 145.239.122.231
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "8%"
    memory = "8%"
    memory.enforce = "soft"
  }
}

