### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr05"
    scheme   = "https"
    address  = "sr05.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r051" {
  name =  "r051"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d4:c3:3c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 92.222.153.216/32   
    gateway4: 92.222.153.216
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r052" {
  name =  "r052"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:37:99:9d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 92.222.153.217/32   
    gateway4: 92.222.153.217
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r053" {
  name =  "r053"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:7b:06:c7"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 92.222.153.218/32   
    gateway4: 92.222.153.218
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r054" {
  name =  "r054"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:b4:8d:81"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 92.222.153.219/32   
    gateway4: 92.222.153.219
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r055" {
  name =  "r055"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:7b:d1:40"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.232/32   
    gateway4: 145.239.122.232
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r056" {
  name =  "r056"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:24:a6:07"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.233/32   
    gateway4: 145.239.122.233
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r057" {
  name =  "r057"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:36:28:07"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.234/32   
    gateway4: 145.239.122.234
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r058" {
  name =  "r058"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:1d:e7:8f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.235/32   
    gateway4: 145.239.122.235
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r059" {
  name =  "r059"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:f6:65:7f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.236/32   
    gateway4: 145.239.122.236
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05a" {
  name =  "r05a"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:9d:15:86"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.237/32   
    gateway4: 145.239.122.237
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05b" {
  name =  "r05b"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:0d:8b:54"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.238/32   
    gateway4: 145.239.122.238
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05c" {
  name =  "r05c"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:0a:07:26"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 145.239.122.239/32   
    gateway4: 145.239.122.239
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05d" {
  name =  "r05d"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:53:a4:4d"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.242.88/32   
    gateway4: 147.135.242.88
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05e" {
  name =  "r05e"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:15:33:b5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.242.89/32   
    gateway4: 147.135.242.89
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05f" {
  name =  "r05f"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:54:d0:48"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.242.90/32   
    gateway4: 147.135.242.90
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r05g" {
  name =  "r05g"
  image     = "zen-base"
  remote = "sr05"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:e2:e8:92"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 147.135.242.91/32   
    gateway4: 147.135.242.91
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}

