### generated by lxd-tf.py ###

variable lxd_trust_password {
  # lxd host access password passed in from command line
}

variable cloud_init_user_data {
  default = <<EOF
#cloud-config
users:
  - name: nladmin
    shell: /bin/bash
    passwd: REDACTED_HASH
    sudo: [ "ALL=(ALL:ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com
  - name: zen
    shell: /bin/bash
    passwd: REDACTED_HASH
    ssh-authorized-keys:
      - ssh-rsa REDACTED_SSH_PUBLIC_KEY admin@example.com

packages:
  - python-minimal
EOF
}

# Configure the LXD Provider
provider "lxd" {
  config_dir = "./"
  generate_client_certificates = true
  accept_remote_certificate    = true


  lxd_remote {
    name     = "sr10"
    scheme   = "https"
    address  = "sr10.4nl.co"
    # password supplied via LXD_TRUST_PASSWORD env var sourced in from ansible vault
    password = "${var.lxd_trust_password}"
  }

}




resource "lxd_container" "r101" {
  name =  "r101"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:5c:b9:f6"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 37.59.252.92/32   
    gateway4: 37.59.252.92
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r102" {
  name =  "r102"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:4a:b1:1c"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 37.59.252.93/32   
    gateway4: 37.59.252.93
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r103" {
  name =  "r103"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:ca:e8:42"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 37.59.252.94/32   
    gateway4: 37.59.252.94
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r104" {
  name =  "r104"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:03:3a:b9"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 37.59.252.95/32   
    gateway4: 37.59.252.95
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r105" {
  name =  "r105"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:e8:09:89"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.0/32   
    gateway4: 51.38.175.0
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r106" {
  name =  "r106"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:1e:bf:e7"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.1/32   
    gateway4: 51.38.175.1
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r107" {
  name =  "r107"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:cb:85:ba"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.2/32   
    gateway4: 51.38.175.2
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r108" {
  name =  "r108"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:ef:aa:75"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.3/32   
    gateway4: 51.38.175.3
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r109" {
  name =  "r109"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:ad:f6:db"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.4/32   
    gateway4: 51.38.175.4
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10a" {
  name =  "r10a"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:99:e7:de"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.5/32   
    gateway4: 51.38.175.5
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10b" {
  name =  "r10b"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:46:0e:f3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.6/32   
    gateway4: 51.38.175.6
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10c" {
  name =  "r10c"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:08:d6:9f"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 51.38.175.7/32   
    gateway4: 51.38.175.7
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10d" {
  name =  "r10d"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d5:66:af"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 10
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.14.232/32   
    gateway4: 213.32.14.232
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10e" {
  name =  "r10e"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:c0:47:d3"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 20
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.14.233/32   
    gateway4: 213.32.14.233
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10f" {
  name =  "r10f"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:f2:f0:f5"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 30
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.14.234/32   
    gateway4: 213.32.14.234
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}



resource "lxd_container" "r10g" {
  name =  "r10g"
  image     = "zen-base"
  remote = "sr10"
  ephemeral = false

  device {
    name = "eth0"
    type = "nic"
    properties {
      nictype = "macvlan"
      parent  = "eno1"
      hwaddr = "02:00:00:d3:cb:dc"
    }
  }

  config {
    boot.autostart = true
    boot.autostart.delay = 0
    linux.kernel_modules = "ip_tables,ip6_tables"
    user.network-config = <<EOF
version: 2
ethernets:
  eth0:
    addresses:
    - 213.32.14.235/32   
    gateway4: 213.32.14.235
    nameservers:
      addresses:
      - 208.67.222.222
      - 208.67.220.22
      search:
      - nodelauncher.com
      - 4nl.co 
EOF
    user.user-data = "${var.cloud_init_user_data}"
  }

  limits {
    cpu.allowance = "6%"
    memory = "6%"
    memory.enforce = "soft"
  }
}

